# Generated by Django 4.2.7 on 2023-11-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('travel_year', models.IntegerField()),
                ('image_url', models.URLField(max_length=500, null=True)),
                ('score', models.FloatField()),
                ('touristic_point', models.CharField(max_length=200)),
                ('analysis', models.CharField(max_length=200)),
            ],
        ),
    ]
