# Generated by Django 4.2.7 on 2023-11-17 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='location',
            new_name='locations',
        ),
    ]
