# Generated by Django 4.2.7 on 2023-11-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='locations',
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(to='locations.category'),
        ),
    ]
